// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // This file is read by the Prisma CLI only (migrate/db/studio/seed); the
    // running app builds its own client in src/lib/prisma.ts. So prefer the
    // direct connection here: Supabase's pooled (pgbouncer, port 6543) URL
    // cannot run migrations, while the app wants the pooled one.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
